version: "2.3"
services:
  dns:
    image: sixeyed/dnsmasq:linux-arm64
    depends_on:
      vpn:
        condition: service_healthy
    entrypoint: dnsmasq
    command:
      - --conf-file=-
      - --log-facility=-
      - --keep-in-foreground
      - --no-hosts
      - --strict-order
      - --listen-address=0.0.0.0
      - --port=1081
      - --bind-interfaces
      - --resolv-file=/etc/resolv.conf
    healthcheck:
      test: [ "CMD-SHELL", "ip -o a show ppp0 >/dev/null 2>&1 || { sleep 60; ip -o a show ppp0 >/dev/null 2>&1 || { kill 1; exit 1; }; }" ]
      interval: 11s
      timeout: 70s
      retries: 3
      start_period: 30s
    network_mode: "service:vpn"
    restart: "always"
    logging:
      driver: ${DNS_LOG_DRIVER:-json-file}
      options:
        max-size: ${DNS_LOG_MAX_SIZE:-2m}
        max-file: ${DNS_LOG_MAX_FILE:-10}
